swagger: '2.0'
info:
  version: 1.0.0
  title: People API
paths:
  /people:
    get:
      summary: Returns all persons
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
  /customers:
    get:
      summary: Returns all customers
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Person'
definitions:
  Person:
    type: object
    properties:
      name:
        type: string
      role:
        type: string
      address:
        type: string
      email:
        type: string